//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShopManagement.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PDVQFLV;Initial Catalog=CoffeeShopManagementDB;Integrated Sec" +
            "urity=True;Encrypt=True;TrustServerCertificate=True")]
        public string CoffeeShopManagementDBConnectionString {
            get {
                return ((string)(this["CoffeeShopManagementDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PDVQFLV;Initial Catalog=CoffeeShopManagementDB;Integrated Sec" +
            "urity=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True")]
        public string CoffeeShopManagementDBConnectionString1 {
            get {
                return ((string)(this["CoffeeShopManagementDBConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.10.104;Initial Catalog=CoffeeShop_DB;User ID=kimluong;Passwor" +
            "d=1234;Connect Timeout=30;Encrypt=True;TrustServerCertificate=True")]
        public string CoffeeShop_DBConnectionString {
            get {
                return ((string)(this["CoffeeShop_DBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PDVQFLV;Initial Catalog=CoffeeShopManagementDB;Integrated Sec" +
            "urity=True;Connect Timeout=30;Encrypt=True;TrustServerCertificate=True")]
        public string CoffeeShopManagementDBConnectionString2 {
            get {
                return ((string)(this["CoffeeShopManagementDBConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-NONF2UG3;Initial Catalog=CoffeeShop_DB;Integrated Security=Tru" +
            "e;Connect Timeout=30;Encrypt=True;TrustServerCertificate=True")]
        public string CoffeeShop_DBConnectionString1 {
            get {
                return ((string)(this["CoffeeShop_DBConnectionString1"]));
            }
        }
    }
}
